version: "3.1"

services:
  tasks_db:
    image: postgres
    container_name: tasks-app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: tasks-app
    ports:
      - 5432:5432
